### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by kfaria** [Anon-Inu/poc-network#6]
- https://www.npmjs.com/package/eslint
- https://www.npmjs.com/package/prettier
- https://www.npmjs.com/package/husky

- [ ] add linting
- [ ] add prettier
- [ ] add husky rules so that we lint and prettify on every push

**Comment by shamoons** [comment]
@jeffreyhshapiro - this one is small, but a good quick fix if you're up for it?

**Comment by jeffreyhshapiro** [comment]
@shamoons sure!

How would we feel about prettying on save, and linting at the PR level? I think it could be frustrating to address the linter on every push

**Comment by shamoons** [comment]
Good call! I’m fine with it. @kfaria , thoughts?

**Comment by kfaria** [comment]
@jeffreyhshapiro I'm cool with prettying on save! And cool with lint on PR, but I think that might require GitHub actions to be set up?  OK with it as well, the free tier has I think 5000 minutes free right? @shamoons

**Comment by shamoons** [comment]
We can start with that. If we run out of free minutes, we’ll figure it out then

**Comment by jeffreyhshapiro** [comment]
cool! just to throw out one more suggestion, if this might be an easier starter, we lint on push BUT all issues are warnings instead of errors. we would just trust that the developer fixes the warnings in his/her work, and reviewers can check too. not ideal but hey its a thought 🤷 

this way we won't set ourselves up for a CI roadblock once we run out of minutes and we have time to think a little more about it

**Comment by shamoons** [comment]
I'm fine with starting with all issues are warnings for now. Later, we can change to errors when we adopt a slightly more strict style guide. With `prettier`, we can set to auto pretty with a `husky` recommit hook so at least silly things like formatting are all consistent.

**Comment by shamoons** [comment]
@kfaria - how do we close this issue?
